security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    access_denied_url: fos_user_security_login
      
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN  }
        - { path: ^/resetting, role: ROLE_ADMIN  }
        - { path: ^/admin/, role: ROLE_ADMIN }   
        - { path: ^/etudiant/, role: ROLE_ADMIN } 
        - { path: ^/$, role: ROLE_USER }
        - { path: ^/aide/$, role: ROLE_USER }
