<?php

namespace Iut\AncienEtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends EntityRepository
{
    public function  getById($id){
        
        $query = $this->createQueryBuilder('e')
                      ->leftJoin('e.poste', 'p')
                      ->addSelect('p')
                      ->where('e.id = :id')
                      ->setParameter('id', $id);
         return $query->getQuery()
                      ->getArrayResult();
    }
    
     
}
