<?php

namespace Iut\AncienEtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
    public function  getById($id){
        $query = $this->createQueryBuilder('f')
                      ->where('f.id = :id')
                      ->setParameter('id', $id);
         return $query->getQuery()
                      ->getArrayResult();
    }
}
